export const climateChangeAbstract = `
Objectives: We aimed to develop a systematic synthesis of systematic reviews of health impacts of climate change, by synthesising studies' characteristics, climate impacts, health outcomes and key findings.

Design: We conducted an overview of systematic reviews of health impacts of climate change. We registered our review in PROSPERO (CRD42019145972). No ethical approval was required since we used secondary data. Additional data are not available.

Data sources: On 22 June 2019, we searched Medline, Cumulative Index to Nursing and Allied Health Literature (CINAHL), Embase, Cochrane and Web of Science.

Eligibility criteria: We included systematic reviews that explored at least one health impact of climate change.

Data extraction and synthesis: We organised systematic reviews according to their key characteristics, including geographical regions, year of publication and authors' affiliations. We mapped the climate effects and health outcomes being studied and synthesised major findings. We used a modified version of A MeaSurement Tool to Assess systematic Reviews-2 (AMSTAR-2) to assess the quality of studies.

Results: We included 94 systematic reviews. Most were published after 2015 and approximately one-fifth contained meta-analyses. Reviews synthesised evidence about five categories of climate impacts; the two most common were meteorological and extreme weather events. Reviews covered 10 health outcome categories; the 3 most common were (1) infectious diseases, (2) mortality and (3) respiratory, cardiovascular or neurological outcomes. Most reviews suggested a deleterious impact of climate change on multiple adverse health outcomes, although the majority also called for more research.

Conclusions: Most systematic reviews suggest that climate change is associated with worse human health. This study provides a comprehensive higher order summary of research on health impacts of climate change. Study limitations include possible missed relevant reviews, no meta-meta-analyses, and no assessment of overlap. Future research could explore the potential explanations between these associations to propose adaptation and mitigation strategies and could include broader sociopsychological health impacts of climate change.
`;

export const invasiveZebraMusselsAbstract = `Freshwater mussels are in decline worldwide, with the depressed river mussel Pseudanodonta complanata being one of the rarest and most endangered species in Europe. Invasive mussels are suspected to be an important factor of decline, but there is little information on their interaction with native species.
This study analyzed densities, depth distribution, and individual sizes and weights in one of the largest known populations of P. complanata in Europe in relation to the co‐occurring invasive zebra mussel Dreissena polymorpha and other mussel species, using a systematic transect analysis.
Pseudanodonta complanata was the dominant unionid species in Lake Siecino reaching densities of up to 26 ind/m2, with half of the specimens found at a water depth of 2.0–4.0 m. Densities were highest on sandy substrates in areas of underwater currents. In contrast, 67% of native Unio tumidus were found at depths < 1 m, indicating different habitat preference.
In the study area, 91% of P. complanata, 92% of U. tumidus, and all Anodonta individuals were fouled by D. polymorpha. The dreissenid:unionid mass ratio (mean ± SD; maximum) was 0.43 ± 0.56; 4.22 and 0.86 ± 1.87; 8.76 in P. complanata and U. tumidus, respectively. Pseudanodonta complanata fouled with D. polymorpha were impaired in their anchoring capability and had shell deformations potentially affecting shell closing and filtration activity. Fouling intensity was negatively correlated with unionid density, potentially leading to accelerated population declines.
The observed adverse effects of invasive zebra mussels on the depressed river mussel and the difficulties in eradicating established populations of invasive mussels suggest that D. polymorpha should be considered a serious threat to P. complanata. Therefore, the further spread of zebra mussels into habitats with native unionids needs to be avoided by all means.`;

export const hockeyYouthConcussionAbstract = `Background: 
Visual symptoms are common after concussion. Rapid automatized naming (RAN) tasks are simple performance measures that demonstrate worse time scores in the setting of acute or more remote injury.

Methods: 
We evaluated the capacity for the Mobile Universal Lexicon Evaluation System (MULES) and Staggered Uneven Number (SUN) testing to be feasibly administered during preseason testing in a cohort of youth ice hockey athletes using a novel computerized app, the Mobile Integrated Cognitive Kit (MICK). Participants from a youth hockey league underwent preseason testing.

Results: 
Among 60 participants, the median age was 13 years (range 6–17). The median best time for the MULES was 49.8 seconds (range = 34.2–141.0) and the median best time for the SUN was 70.1 (range = 36.6–200.0). As is characteristic of timed performance measures, there were learning effects between the first and second trials for both the MULES (median improvement = 10.6 seconds, range = −32.3 to 92.0, P < 0.001, Wilcoxon signed-rank test) and SUN (median improvement = 2.4 seconds, range= −8.0 to 15.1, P = 0.001, Wilcoxon signed-rank test). Age was a predictor of best baseline times, with longer (worse) times for younger participants for MULES (P < 0.001, rs = −0.67) and SUN (P < 0.001, rs = −0.54 Spearman rank correlation). Degrees of learning effect did not vary with age (P > 0.05, rs = −0.2).

Conclusions: 
Vision-based RAN tasks, such as the MULES and SUN, can be feasibly administered using the MICK app during preseason baseline testing in youth sports teams. The results suggest that more frequent baseline tests are necessary for preadolescent athletes because of the relation of RAN task performance to age.`;

export const coralReefsAbstract = `Climate change is impacting coral reefs now. Recent pan-tropical bleaching events driven by unprecedented global heat waves have shifted the playing field for coral reef management and policy. While best-practice conventional management remains essential, it may no longer be enough to sustain coral reefs under continued climate change. Nor will climate change mitigation be sufficient on its own. Committed warming and projected reef decline means solutions must involve a portfolio of mitigation, best-practice conventional management and coordinated restoration and adaptation measures involving new and perhaps radical interventions, including local and regional cooling and shading, assisted coral evolution, assisted gene flow, and measures to support and enhance coral recruitment. We propose that proactive research and development to expand the reef management toolbox fast but safely, combined with expedient trialling of promising interventions is now urgently needed, whatever emissions trajectory the world follows. We discuss the challenges and opportunities of embracing new interventions in a race against time, including their risks and uncertainties. Ultimately, solutions to the climate challenge for coral reefs will require consideration of what society wants, what can be achieved technically and economically, and what opportunities we have for action in a rapidly closing window. Finding solutions that work for coral reefs and people will require exceptional levels of coordination of science, management and policy, and open engagement with society. It will also require compromise, because reefs will change under climate change despite our best interventions. We argue that being clear about society’s priorities, and understanding both the opportunities and risks that come with an expanded toolset, can help us make the most of a challenging situation. We offer a conceptual model to help reef managers frame decision problems and objectives, and to guide effective strategy choices in the face of complexity and uncertainty.`;
